springdoc:
  api-docs:
    path: /api-docs/json
    groups:
      enabled: 'true'
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  version: v1.0.0
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs
  cache:
    disabled: 'true'
  packages-to-scan: com.backend.nutt
